[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["app"]
known_third_party = [
    "fastapi", "uvicorn", "pydantic", "redis", "asyncpg", "pika",
    "prometheus_client", "psutil", "openai", "langchain", "torch",
    "scikit-learn", "pandas", "numpy", "mlflow", "matplotlib", "seaborn",
    "python-dotenv", "pytz", "traceloggerx", "pytest", "selenium",
    "beautifulsoup4", "requests", "PyJWT", "bcrypt", "passlib"
]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
force_sort_within_sections = true
combine_as_imports = true
skip_glob = ["**/migrations/*", "**/venv/*", "**/node_modules/*"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
  | venv
  | node_modules
)/
'''
